/**
 * Codegen script for Hangul syllable decomposition/composition tables.
 *
 * To generate, run `npm run codegen`.
 *
 * Generates:
 *   - `src/generated/jamo-table.gen.ts`   — ChoTable, JungTable, and JongTable
 *     (compatibility jamo to concatenated modern Hangul syllable strings)
 *   - `src/generated/compose-table.gen.ts` — ComposeTable (jamo triple to syllable)
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  CHOSEONG,
  JONGSEONG,
  JUNGSEONG,
  L_COUNT,
  N_COUNT,
  S_BASE,
  S_END,
  T_COUNT,
  V_COUNT,
} from "../src/hangul-unicode/runtime.js";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Add a compatibility jamo here if the conjugation engine inserts a new jongseong.
const COMPOSE_JONG = [null, "ㄴ", "ㄹ", "ㅂ", "ㅆ"] as const;

/**
 * Compose a syllable from jamo indices.
 * Returns the codepoint: SBase + (cho * NCount) + (jung * TCount) + jong
 */
function composeSyllable(
  choIdx: number,
  jungIdx: number,
  jongIdx: number,
): number {
  return S_BASE + choIdx * N_COUNT + jungIdx * T_COUNT + jongIdx;
}

/**
 * Decompose a Hangul syllable codepoint into choseong, jungseong, jongseong indices,
 * then map each to its compatibility jamo character.
 */
function decompose(code: number) {
  const sIndex = code - S_BASE;
  const lIndex = Math.floor(sIndex / N_COUNT);
  const vIndex = Math.floor((sIndex % N_COUNT) / T_COUNT);
  const tIndex = sIndex % T_COUNT;
  return {
    cho: CHOSEONG[lIndex],
    jung: JUNGSEONG[vIndex],
    jong: JONGSEONG[tIndex],
  };
}

// Table generation

/**
 * Generate a reverse lookup table from compatibility jamo to syllable blobs.
 */
function genBlobTable(
  name: string,
  keys: readonly (string | null)[],
  groups: string[][],
): string[] {
  return [
    `export type ${name} = {`,
    ...keys.map(
      (key, index) => `  "${key ?? "NULL"}": "${groups[index].join("")}";`,
    ),
    "};",
    "",
  ];
}

/** Distribute U+AC00–U+D7A3 into the three reverse lookup tables. */
function genJamoTables(): string {
  const choGroups = CHOSEONG.map(() => [] as string[]);
  const jungGroups = JUNGSEONG.map(() => [] as string[]);
  const jongGroups = JONGSEONG.map(() => [] as string[]);

  for (let code = S_BASE; code <= S_END; code++) {
    const char = String.fromCharCode(code);
    const { cho, jung, jong } = decompose(code);
    choGroups[CHOSEONG.indexOf(cho)].push(char);
    jungGroups[JUNGSEONG.indexOf(jung)].push(char);
    jongGroups[JONGSEONG.indexOf(jong)].push(char);
  }

  return [
    "// @generated by scripts/gen-jamo-table.ts — DO NOT EDIT",
    "",
    ...genBlobTable("ChoTable", CHOSEONG, choGroups),
    ...genBlobTable("JungTable", JUNGSEONG, jungGroups),
    ...genBlobTable("JongTable", JONGSEONG, jongGroups),
    'export type OpenSyllable = JongTable["NULL"];',
    "",
  ].join("\n");
}

/**
 * Generate the finite cross-product used by the conjugation engine.
 */
function genComposeTable(): string {
  const entries: Array<{ key: string; char: string }> = [];

  for (let cho = 0; cho < CHOSEONG.length; cho++) {
    for (let jung = 0; jung < JUNGSEONG.length; jung++) {
      for (const jong of COMPOSE_JONG) {
        const jongIdx = jong === null ? 0 : JONGSEONG.indexOf(jong);
        entries.push({
          key:
            jong === null
              ? `${CHOSEONG[cho]}_${JUNGSEONG[jung]}`
              : `${CHOSEONG[cho]}_${JUNGSEONG[jung]}_${jong}`,
          char: String.fromCharCode(composeSyllable(cho, jung, jongIdx)),
        });
      }
    }
  }

  const lines: string[] = [];
  lines.push("// @generated by scripts/gen-jamo-table.ts — DO NOT EDIT");
  lines.push("");
  lines.push("export type ComposeTable = {");
  for (const { key, char } of entries) {
    lines.push(`  "${key}": "${char}";`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

// Output

const outDir = resolve(__dirname, "../src/generated");

const jamoFileContent = genJamoTables();
writeFileSync(resolve(outDir, "jamo-table.gen.ts"), jamoFileContent, "utf-8");
console.log(
  `Done: src/generated/jamo-table.gen.ts (ChoTable: ${L_COUNT}, JungTable: ${V_COUNT}, JongTable: ${T_COUNT} keys)`,
);

const composeContent = genComposeTable();
const composeEntryCount = L_COUNT * V_COUNT * COMPOSE_JONG.length;
writeFileSync(resolve(outDir, "compose-table.gen.ts"), composeContent, "utf-8");
console.log(
  `Done: src/generated/compose-table.gen.ts (${composeEntryCount} entries)`,
);
