/**
 * Codegen script for Hangul syllable decomposition/composition tables.
 *
 * To generate, run `npm run codegen`.
 *
 * Generates:
 *   - `src/generated/jamo-table.gen.ts`   — OpenSyllable (union of all syllables
 *     without jongseong) + JamoTable (all modern Hangul syllables mapped to jamo)
 *   - `src/generated/compose-table.gen.ts` — ComposeTable (jamo triple to syllable)
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Unicode constants for Hangul syllable block

const S_BASE = 0xac00; // '가' (first syllable)
const S_END = 0xd7a3; // '힣' (last syllable)
const L_COUNT = 19; // choseong (initial consonant) count
const V_COUNT = 21; // jungseong (medial vowel) count
const T_COUNT = 28; // jongseong (final consonant) count, including none
const N_COUNT = V_COUNT * T_COUNT; // 588

/** Compatibility jamo — the user-facing forms mapped from algorithmic indices. */
const CHOSEONG: string[] = [
  "ㄱ",
  "ㄲ",
  "ㄴ",
  "ㄷ",
  "ㄸ",
  "ㄹ",
  "ㅁ",
  "ㅂ",
  "ㅃ",
  "ㅅ",
  "ㅆ",
  "ㅇ",
  "ㅈ",
  "ㅉ",
  "ㅊ",
  "ㅋ",
  "ㅌ",
  "ㅍ",
  "ㅎ",
];

const JUNGSEONG: string[] = [
  "ㅏ",
  "ㅐ",
  "ㅑ",
  "ㅒ",
  "ㅓ",
  "ㅔ",
  "ㅕ",
  "ㅖ",
  "ㅗ",
  "ㅘ",
  "ㅙ",
  "ㅚ",
  "ㅛ",
  "ㅜ",
  "ㅝ",
  "ㅞ",
  "ㅟ",
  "ㅠ",
  "ㅡ",
  "ㅢ",
  "ㅣ",
];

const JONGSEONG: (string | null)[] = [
  null,
  "ㄱ",
  "ㄲ",
  "ㄳ",
  "ㄴ",
  "ㄵ",
  "ㄶ",
  "ㄷ",
  "ㄹ",
  "ㄺ",
  "ㄻ",
  "ㄼ",
  "ㄽ",
  "ㄾ",
  "ㄿ",
  "ㅀ",
  "ㅁ",
  "ㅂ",
  "ㅄ",
  "ㅅ",
  "ㅆ",
  "ㅇ",
  "ㅈ",
  "ㅊ",
  "ㅋ",
  "ㅌ",
  "ㅍ",
  "ㅎ",
];

// Add a compatibility jamo here if the conjugation engine inserts a new jongseong.
const COMPOSE_JONG = [null, "ㄴ", "ㄹ", "ㅂ", "ㅆ"] as const;

/**
 * Compose a syllable from jamo indices.
 * Returns the codepoint: SBase + (cho * NCount) + (jung * TCount) + jong
 */
function composeSyllable(
  choIdx: number,
  jungIdx: number,
  jongIdx: number,
): number {
  return S_BASE + choIdx * N_COUNT + jungIdx * T_COUNT + jongIdx;
}

/**
 * Decompose a Hangul syllable codepoint into choseong, jungseong, jongseong indices,
 * then map each to its compatibility jamo character.
 */
function decompose(code: number) {
  const sIndex = code - S_BASE;
  const lIndex = Math.floor(sIndex / N_COUNT);
  const vIndex = Math.floor((sIndex % N_COUNT) / T_COUNT);
  const tIndex = sIndex % T_COUNT;
  return {
    cho: CHOSEONG[lIndex],
    jung: JUNGSEONG[vIndex],
    jong: JONGSEONG[tIndex],
  };
}

// Table generation

/**
 * Generate `OpenSyllable` and the exhaustive modern-Hangul `JamoTable`
 * together from the U+AC00–U+D7A3 syllable block.
 */
function genJamoTable(): string {
  const openSyllables: string[] = [];
  const entries: string[] = [];
  for (let code = S_BASE; code <= S_END; code++) {
    const char = String.fromCharCode(code);
    const { cho, jung, jong } = decompose(code);
    if (jong === null) openSyllables.push(char);
    entries.push(
      `  "${char}": { 초: "${cho}"; 중: "${jung}"; 종: ${jong === null ? "null" : `"${jong}"`} };`,
    );
  }

  const lines: string[] = [];
  lines.push("// @generated by scripts/gen-jamo-table.ts — DO NOT EDIT");
  lines.push("");
  lines.push("export type OpenSyllable =");
  for (let i = 0; i < openSyllables.length; i++) {
    const sep = i === openSyllables.length - 1 ? ";" : "";
    lines.push(`  | "${openSyllables[i]}"${sep}`);
  }
  lines.push("");
  lines.push("export type JamoTable = {");
  lines.push(...entries);
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate the finite cross-product used by the conjugation engine.
 */
function genComposeTable(): string {
  const entries: Array<{ key: string; char: string }> = [];

  for (let cho = 0; cho < CHOSEONG.length; cho++) {
    for (let jung = 0; jung < JUNGSEONG.length; jung++) {
      for (const jong of COMPOSE_JONG) {
        const jongIdx = jong === null ? 0 : JONGSEONG.indexOf(jong);
        entries.push({
          key:
            jong === null
              ? `${CHOSEONG[cho]}_${JUNGSEONG[jung]}`
              : `${CHOSEONG[cho]}_${JUNGSEONG[jung]}_${jong}`,
          char: String.fromCharCode(composeSyllable(cho, jung, jongIdx)),
        });
      }
    }
  }

  const lines: string[] = [];
  lines.push("// @generated by scripts/gen-jamo-table.ts — DO NOT EDIT");
  lines.push("");
  lines.push("export type ComposeTable = {");
  for (const { key, char } of entries) {
    lines.push(`  "${key}": "${char}";`);
  }
  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

// Output

const outDir = resolve(__dirname, "../src/generated");

const jamoFileContent = genJamoTable();
const openSyllableCount = L_COUNT * V_COUNT;
writeFileSync(resolve(outDir, "jamo-table.gen.ts"), jamoFileContent, "utf-8");
console.log(
  `Done: src/generated/jamo-table.gen.ts (OpenSyllable: ${openSyllableCount}, JamoTable: ${S_END - S_BASE + 1} entries)`,
);

const composeContent = genComposeTable();
const composeEntryCount = L_COUNT * V_COUNT * COMPOSE_JONG.length;
writeFileSync(resolve(outDir, "compose-table.gen.ts"), composeContent, "utf-8");
console.log(
  `Done: src/generated/compose-table.gen.ts (${composeEntryCount} entries)`,
);
