/**
 * Codegen script for Hangul syllable decomposition/composition tables.
 *
 * Generates:
 *   - `src/generated/jamo-table.gen.ts`   — JamoTable (syllable to jamo (자모) breakdown)
 *   - `src/generated/compose-table.gen.ts` — ComposeTable (jamo triple to syllable)
 */

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Unicode constants for Hangul syllable block

const S_BASE = 0xac00; // '가' (first syllable)
const L_COUNT = 19; // choseong (initial consonant) count
const V_COUNT = 21; // jungseong (medial vowel) count
const T_COUNT = 28; // jongseong (final consonant) count, including none
const N_COUNT = V_COUNT * T_COUNT; // 588

/** Compatibility jamo — the user-facing forms mapped from algorithmic indices. */
const CHOSEONG: string[] = [
  "ㄱ",
  "ㄲ",
  "ㄴ",
  "ㄷ",
  "ㄸ",
  "ㄹ",
  "ㅁ",
  "ㅂ",
  "ㅃ",
  "ㅅ",
  "ㅆ",
  "ㅇ",
  "ㅈ",
  "ㅉ",
  "ㅊ",
  "ㅋ",
  "ㅌ",
  "ㅍ",
  "ㅎ",
];

const JUNGSEONG: string[] = [
  "ㅏ",
  "ㅐ",
  "ㅑ",
  "ㅒ",
  "ㅓ",
  "ㅔ",
  "ㅕ",
  "ㅖ",
  "ㅗ",
  "ㅘ",
  "ㅙ",
  "ㅚ",
  "ㅛ",
  "ㅜ",
  "ㅝ",
  "ㅞ",
  "ㅟ",
  "ㅠ",
  "ㅡ",
  "ㅢ",
  "ㅣ",
];

const JONGSEONG: (string | null)[] = [
  null,
  "ㄱ",
  "ㄲ",
  "ㄳ",
  "ㄴ",
  "ㄵ",
  "ㄶ",
  "ㄷ",
  "ㄹ",
  "ㄺ",
  "ㄻ",
  "ㄼ",
  "ㄽ",
  "ㄾ",
  "ㄿ",
  "ㅀ",
  "ㅁ",
  "ㅂ",
  "ㅄ",
  "ㅅ",
  "ㅆ",
  "ㅇ",
  "ㅈ",
  "ㅊ",
  "ㅋ",
  "ㅌ",
  "ㅍ",
  "ㅎ",
];

/**
 * Decompose a Hangul syllable codepoint into choseong, jungseong, jongseong indices,
 * then map each to its compatibility jamo character.
 */
function decompose(code: number) {
  const sIndex = code - S_BASE;
  const lIndex = Math.floor(sIndex / N_COUNT);
  const vIndex = Math.floor((sIndex % N_COUNT) / T_COUNT);
  const tIndex = sIndex % T_COUNT;
  return {
    cho: CHOSEONG[lIndex],
    jung: JUNGSEONG[vIndex],
    jong: JONGSEONG[tIndex],
  };
}

/**
 * Generate `JamoTable` — maps each syllable to `{ 초: choseong; 중: jungseong; 종: jongseong | null }`.
 */
function genJamoTable(): string {
  const lines: string[] = [];
  lines.push("// @generated by scripts/gen-jamo-table.ts — DO NOT EDIT");
  lines.push("");
  lines.push("export type JamoTable = {");

  for (let i = 0; i < L_COUNT * N_COUNT; i++) {
    const code = S_BASE + i;
    const char = String.fromCharCode(code);
    const { cho, jung, jong } = decompose(code);
    const jongValue = jong === null ? "null" : `"${jong}"`;
    lines.push(
      `  "${char}": { 초: "${cho}"; 중: "${jung}"; 종: ${jongValue} };`,
    );
  }

  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

/**
 * Generate `ComposeTable` — reverse mapping from `"초_중_종"` key to a composed syllable.
 */
function genComposeTable(): string {
  const lines: string[] = [];
  lines.push("// @generated by scripts/gen-jamo-table.ts — DO NOT EDIT");
  lines.push("");
  lines.push("export type ComposeTable = {");

  for (let i = 0; i < L_COUNT * N_COUNT; i++) {
    const code = S_BASE + i;
    const char = String.fromCharCode(code);
    const { cho, jung, jong } = decompose(code);
    const key = `${cho}_${jung}_${jong ?? "null"}`;
    lines.push(`  "${key}": "${char}";`);
  }

  lines.push("};");
  lines.push("");
  return lines.join("\n");
}

// Write output files

const outDir = resolve(__dirname, "../src/generated");

writeFileSync(resolve(outDir, "jamo-table.gen.ts"), genJamoTable(), "utf-8");
console.log(
  `Done: src/generated/jamo-table.gen.ts (${L_COUNT * N_COUNT} entries)`,
);

writeFileSync(
  resolve(outDir, "compose-table.gen.ts"),
  genComposeTable(),
  "utf-8",
);
console.log(
  `Done: src/generated/compose-table.gen.ts (${L_COUNT * N_COUNT} entries)`,
);
